package com.libra.apollo.analytics.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import lombok.Data;
import lombok.EqualsAndHashCode;

@Entity
@Table(name = "analytics.analytics")
@SuppressWarnings("serial")
@Data 
@EqualsAndHashCode(callSuper=true)
public class Analytics extends AutoGeneratedId {
	
	@NotNull
	@Column(name="name")
	private String name;
	
	@Column(name="description")
	private String desc;
	
	@NotNull
	@Enumerated(EnumType.STRING)
	private RunType runType;
	
	private SortDirection sortDirectory;
	
}
