package com.libra.apollo.analytics.entity;

import javax.persistence.DiscriminatorColumn;
import javax.persistence.DiscriminatorType;
import javax.persistence.Entity;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.Table;

@SuppressWarnings("serial")
@Entity
@Inheritance(strategy=InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(name="kind", discriminatorType=DiscriminatorType.STRING)
@Table(name="investment_criteria", schema="analytics")
public abstract class Condition extends AutoGeneratedId {
	
	
}
