package com.libra.apollo.analytics.entity;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import lombok.Data;
import lombok.EqualsAndHashCode;

@SuppressWarnings("serial")
@Entity
@Table(name="investment_criteria", schema="analytics")
@EqualsAndHashCode(callSuper=true)
public @Data class Criteria extends AutoGeneratedId {
	
	@OneToMany(mappedBy="criteria")
	List<InvestmentStyleCriteria> investmentStyleCriterias;
	
	@Column(name="factor", nullable=false)
	private String factor;
	
	@Column(name="parameter", nullable=false)
	private double parameter;
	
}
