package com.libra.apollo.analytics.entity;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import com.libra.apollo.analytics.entity.enums.DataSourceType;

@Entity
@Table(name = "analytics_data_source", schema="analytics")
public class DataSource extends AutoGeneratedId {

	/**
	 * 
	 */
	private static final long serialVersionUID = -437609539372574160L;
	
	@NotNull
	@Column(name="type")
	@Enumerated(EnumType.STRING)
	private DataSourceType dataSourceType;
	
	@Column(name="url_base")
	private String urlBase;
	
	@Column(name="clazz_name")
	private String clazzName;
	
	@OneToMany(mappedBy="dataSource")
	private List<InvestmentStyleParameter> investmentStyleParameter;

	public DataSourceType getDataSourceType() {
		return dataSourceType;
	}

	public void setDataSourceType(DataSourceType dataSourceType) {
		this.dataSourceType = dataSourceType;
	}

	public String getUrlBase() {
		return urlBase;
	}

	public void setUrlBase(String urlBase) {
		this.urlBase = urlBase;
	}

	public String getClazzName() {
		return clazzName;
	}

	public void setClazzName(String clazzName) {
		this.clazzName = clazzName;
	}

	public List<InvestmentStyleParameter> getInvestmentStyleParameter() {
		return investmentStyleParameter;
	}

	public void setInvestmentStyleParameter(List<InvestmentStyleParameter> investmentStyleParameter) {
		this.investmentStyleParameter = investmentStyleParameter;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}
	
	
}
