package com.libra.apollo.analytics.entity;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import lombok.Data;
import lombok.EqualsAndHashCode;

@Entity
@Table(name = "data_source")
@Data
@EqualsAndHashCode(callSuper = true)
public class DataSource extends AutoGeneratedId {

	/**
	 * 
	 */
	private static final long serialVersionUID = -437609539372574160L;
	
	@NotNull
	@Column(name="data_source_type")
	@Enumerated(EnumType.STRING)
	private DataSourceType dataSourceType;
	
	@Column(name="url_base")
	private String urlBase;
	
	@Column(name="clazz_name")
	private String clazzName;
	
	@OneToMany(mappedBy="dataSource")
	private List<InvestmentStyleDataSource> investmentStyleConditions;
	
	
}
