package com.libra.apollo.analytics.entity;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

//SELECT instrument_id , max(stamp_date) as max_stamp_date FROM apollo.stockindicators group by instrument_id

@Entity
@Immutable
@Table(name = "indicators_top_stamp_date")
public class IndicatorsTopStampDate extends ImmutableAutoGeneratedId {

	private Long stockId;
	private Date maxStampDate;

	public Long getStockId() {
		return stockId;
	}

	public void setStockId(Long stockId) {
		this.stockId = stockId;
	}

	public Date getMaxStampDate() {
		return maxStampDate;
	}

	public void setMaxStampDate(Date maxStampDate) {
		this.maxStampDate = maxStampDate;
	}

}
