package com.libra.apollo.analytics.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Table;

import lombok.Data;
import lombok.EqualsAndHashCode;

@SuppressWarnings("serial")
@Entity
@Table(name="criteria", schema="analytics")
@EqualsAndHashCode(callSuper=true)
public @Data class InvestmentCriteria extends AutoGeneratedId {
	
	@Column(name="factor", nullable=false)
	private String factor;
	
	@Column(name="value", nullable=false)
	private double value;
	
	@Enumerated(EnumType.STRING)
	private Operation operator;
	
}
