package com.libra.apollo.analytics.entity;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Immutable;
import org.hibernate.annotations.Type;

import com.libra.apollo.analytics.entity.listener.PreventUpdateListener;
import com.libra.apollo.analytics.entity.type.CustomBigDecimal;
import com.libra.apollo.analytics.entity.type.IndicatorBigDecimal;

import lombok.Data;
import lombok.EqualsAndHashCode;

@Entity
@Table(name = "stockindicators")
@EntityListeners(PreventUpdateListener.class)
@Data
@EqualsAndHashCode(callSuper=false)
//@Immutable
public class LibraStockIndicators extends AutoGeneratedId implements Comparable<LibraStockIndicators> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 222263006260457523L;

	@Temporal(TemporalType.DATE)
	@Column(name = "stamp_date", nullable = false)
	private Date stampDate;
	
//	@Type(type = "com.libra.apollo.analytics.entity.type.IndicatorBigDecimal")
	@Column(name = "open_price", precision = 19, scale = 4)
	private BigDecimal openPrice;
	
//	@Type(type = IndicatorBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "high_price", precision = 19, scale = 4)
//	private BigDecimal highPrice;
//	
//	@Type(type = IndicatorBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "low_price", precision = 19, scale = 4)
//	private BigDecimal lowPrice;
//	
//	@Type(type = IndicatorBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "close_price", precision = 19, scale = 4)
//	private BigDecimal closePrice;
//	
//	@Type(type = IndicatorBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "volume", precision = 19, scale = 4)
//	private BigDecimal volume;
//
//	@Type(type = IndicatorBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "close_price_1d", precision = 19, scale = 4)
//	private BigDecimal closePrice1D;
//	
//	@Type(type = IndicatorBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "close_price_5d", precision = 19, scale = 4)
//	private BigDecimal closePrice5D;
//	
//	@Type(type = IndicatorBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "close_price_1m", precision = 19, scale = 4)
//	private BigDecimal closePrice1M;
//	
//	@Type(type = IndicatorBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "close_price_3m", precision = 19, scale = 4)
//	private BigDecimal closePrice3M;
//
//	@Type(type = IndicatorBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "shares_outstanding", precision = 19, scale = 4)
//	private BigDecimal sharesOutstanding;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "long_term_growth", precision = 19, scale = 4)
//	private BigDecimal longTermGrowth;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "price_to_earnings_growth_next12m", precision = 19, scale = 4)
//	private BigDecimal priceToEarningsGrowthNext12M;
//	
//	@Column(name = "fiscal_year_end_date", nullable = true)
//	private Date fiscalYearEndDate;
//	
//	@Column(name = "fiscal_year_end_date_fy1", nullable = true)
//	private Date fiscalYearEndDateFY1;
//	
//	@Column(name = "reporting_date_fy0", nullable = true)
//	private Date reportingDateFY0;
//	
//	@Column(name = "reporting_date_flag_fy0")
//	private Integer reportingDateFlagFY0;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "eps_fy0", precision = 19, scale = 4)
//	private BigDecimal epsFY0;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "cash_flow_per_share_fy0", precision = 19, scale = 4)
//	private BigDecimal cashFlowPerShareFY0;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "sales_fy0", precision = 19, scale = 4)
//	private BigDecimal salesFY0;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "book_value_fy0", precision = 19, scale = 4)
//	private BigDecimal bookValueFY0;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "ebitd_fy0", precision = 19, scale = 4)
//	private BigDecimal ebitdFY0;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "price_to_earnings_fy0", precision = 19, scale = 4)
//	private BigDecimal priceToEarningsFY0;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "price_to_cash_flow_fy0", precision = 19, scale = 4)
//	private BigDecimal priceToCashFlowFY0;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "price_to_book_fy0", precision = 19, scale = 4)
//	private BigDecimal priceToBookFY0;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "price_to_ebitd_fy0", precision = 19, scale = 4)
//	private BigDecimal priceToEbitdaFY0;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "market_cap_to_sales_fy0", precision = 19, scale = 4)
//	private BigDecimal marketCapToSalesFY0;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "return_on_equity_fy0", precision = 19, scale = 4)
//	private BigDecimal returnOnEquityFY0;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "eps_growth_fy0", precision = 19, scale = 4)
//	private BigDecimal epsGrowthFY0;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "yield_fy0", precision = 19, scale = 4)
//	private BigDecimal yieldFY0;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "eps_fy0a", precision = 19, scale = 4)
//	private BigDecimal epsFY0a;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "cash_flow_per_share_fy0a", precision = 19, scale = 4)
//	private BigDecimal cashFlowPerShareFY0a;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "book_value_fy0a", precision = 19, scale = 4)
//	private BigDecimal bookValueFY0a;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "ebitd_fy0a", precision = 19, scale = 4)
//	private BigDecimal ebitdFY0a;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "sales_fy0a", precision = 19, scale = 4)
//	private BigDecimal salesFY0a;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "price_to_earnings_fy0a", precision = 19, scale = 4)
//	private BigDecimal priceToEarningsFY0a;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "price_to_cash_flow_fy0a", precision = 19, scale = 4)
//	private BigDecimal priceToCashFlowFY0a;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "price_to_book_fy0a", precision = 19, scale = 4)
//	private BigDecimal priceToBookFY0a;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "price_to_ebitd_fy0a", precision = 19, scale = 4)
//	private BigDecimal priceToEbitdaFY0a;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "market_cap_to_sales_fy0a", precision = 19, scale = 4)
//	private BigDecimal marketCapToSalesFY0a;
//	
//	@Column(name = "reporting_date_fy1", nullable = true)
//	private Date reportingDateFY1;
//	
//	@Column(name = "reporting_date_flag_fy1")
//	private Integer reportingDateFlagFY1;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "eps_fy1", precision = 19, scale = 4)
//	private BigDecimal epsFY1;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "cash_flow_per_share_fy1", precision = 19, scale = 4)
//	private BigDecimal cashFlowPerShareFY1;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "sales_fy1", precision = 19, scale = 4)
//	private BigDecimal salesFY1;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "book_value_fy1", precision = 19, scale = 4)
//	private BigDecimal bookValueFY1;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "ebitd_fy1", precision = 19, scale = 4)
//	private BigDecimal ebitdFY1;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "price_to_earnings_fy1", precision = 19, scale = 4)
//	private BigDecimal priceToEarningsFY1;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "price_to_cash_flow_fy1", precision = 19, scale = 4)
//	private BigDecimal priceToCashFlowFY1;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "price_to_book_fy1", precision = 19, scale = 4)
//	private BigDecimal priceToBookFY1;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "price_to_ebitd_fy1", precision = 19, scale = 4)
//	private BigDecimal priceToEbitdaFY1;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "market_cap_to_sales_fy1", precision = 19, scale = 4)
//	private BigDecimal marketCapToSalesFY1;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "return_on_equity_fy1", precision = 19, scale = 4)
//	private BigDecimal returnOnEquityFY1;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "eps_growth_fy1", precision = 19, scale = 4)
//	private BigDecimal epsGrowthFY1;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "yield_fy1", precision = 19, scale = 4)
//	private BigDecimal yieldFY1;
//	
//	@Column(name = "no_eps_fy1")
//	private Integer noEPSFY1;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "standard_deviation_eps_fy1", precision = 19, scale = 4)
//	private BigDecimal standardDeviationEPSFY1;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "eps_fy1_revisions_1w", precision = 19, scale = 4)
//	private BigDecimal epsFY1Revisions1W;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "eps_fy1_revisions_1m", precision = 19, scale = 4)
//	private BigDecimal epsFY1Revisions1M;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "eps_fy1_revisions_2m", precision = 19, scale = 4)
//	private BigDecimal epsFY1Revisions2M;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "eps_fy1_revisions_3m", precision = 19, scale = 4)
//	private BigDecimal epsFY1Revisions3M;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "eps_fy1_revisions_6m", precision = 19, scale = 4)
//	private BigDecimal epsFY1Revisions6M;
//	
//	@Column(name = "eps_fy1_revisions_up")
//	private Integer epsFY1RevisionsUp;
//	
//	@Column(name = "eps_fy1_revisions_down")
//	private Integer epsFY1RevisionsDown;
//	
//	@Column(name = "eps_fy1_revisions_unchanged")
//	private Integer epsFY1RevisionsUnchanged;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "price_to_earnings_growth_fy1", precision = 19, scale = 4)
//	private BigDecimal priceToEarningsGrowthFY1;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "eps_fy1a", precision = 19, scale = 4)
//	private BigDecimal epsFY1a;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "cash_flow_per_share_fy1a", precision = 19, scale = 4)
//	private BigDecimal cashFlowPerShareFY1a;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "book_value_fy1a", precision = 19, scale = 4)
//	private BigDecimal bookValueFY1a;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "ebitd_fy1a", precision = 19, scale = 4)
//	private BigDecimal ebitdFY1a;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "sales_fy1a", precision = 19, scale = 4)
//	private BigDecimal salesFY1a;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "price_to_earnings_fy1a", precision = 19, scale = 4)
//	private BigDecimal priceToEarningsFY1a;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "price_to_cash_flow_fy1a", precision = 19, scale = 4)
//	private BigDecimal priceToCashFlowFY1a;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "price_to_book_fy1a", precision = 19, scale = 4)
//	private BigDecimal priceToBookFY1a;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "price_to_ebitd_fy1a", precision = 19, scale = 4)
//	private BigDecimal priceToEbitdaFY1a;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "market_cap_to_sales_fy1a", precision = 19, scale = 4)
//	private BigDecimal marketCapToSalesFY1a;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "return_on_equity_fy1a", precision = 19, scale = 4)
//	private BigDecimal returnOnEquityFY1a;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "eps_fy2", precision = 19, scale = 4)
//	private BigDecimal epsFY2;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "cash_flow_per_share_fy2", precision = 19, scale = 4)
//	private BigDecimal cashFlowPerShareFY2;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "sales_fy2", precision = 19, scale = 4)
//	private BigDecimal salesFY2;
//	
//	@Basic(optional = true)
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "book_value_fy2", precision = 19, scale = 4)
//	private BigDecimal bookValueFY2;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "ebitd_fy2", precision = 19, scale = 4)
//	private BigDecimal ebitdFY2;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "price_to_earnings_fy2", precision = 19, scale = 4)
//	private BigDecimal priceToEarningsFY2;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "price_to_cash_flow_fy2", precision = 19, scale = 4)
//	private BigDecimal priceToCashFlowFY2;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "price_to_book_fy2", precision = 19, scale = 4)
//	private BigDecimal priceToBookFY2;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "price_to_ebitd_fy2", precision = 19, scale = 4)
//	private BigDecimal priceToEbitdaFY2;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "market_cap_to_sales_fy2", precision = 19, scale = 4)
//	private BigDecimal marketCapToSalesFY2;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "return_on_equity_fy2", precision = 19, scale = 4)
//	private BigDecimal returnOnEquityFY2;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "eps_growth_fy2", precision = 19, scale = 4)
//	private BigDecimal epsGrowthFY2;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "yield_fy2", precision = 19, scale = 4)
//	private BigDecimal yieldFY2;
//	
//	@Column(name = "no_eps_fy2")
//	private Integer noEPSFY2;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "standard_deviation_eps_fy2", precision = 19, scale = 4)
//	private BigDecimal standardDeviationEPSFY2;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "eps_fy2_revisions_1w", precision = 19, scale = 4)
//	private BigDecimal epsFY2Revisions1W;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "eps_fy2_revisions_1m", precision = 19, scale = 4)
//	private BigDecimal epsFY2Revisions1M;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "eps_fy2_revisions_2m", precision = 19, scale = 4)
//	private BigDecimal epsFY2Revisions2M;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "eps_fy2_revisions_3m", precision = 19, scale = 4)
//	private BigDecimal epsFY2Revisions3M;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "eps_fy2_revisions_6m", precision = 19, scale = 4)
//	private BigDecimal epsFY2Revisions6M;
//	
//	@Column(name = "eps_fy2_revisions_up")
//	private Integer epsFY2RevisionsUp;
//	
//	@Column(name = "eps_fy2_revisions_down")
//	private Integer epsFY2RevisionsDown;
//	
//	@Column(name = "eps_fy2_revisions_unchanged")
//	private Integer epsFY2RevisionsUnchanged;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "price_to_earnings_growth_fy2", precision = 19, scale = 4)
//	private BigDecimal priceToEarningsGrowthFY2;
//	
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "eps_fy2a", precision = 19, scale = 4)
//	private BigDecimal epsFY2a;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "cash_flow_per_share_fy2a", precision = 19, scale = 4)
//	private BigDecimal cashFlowPerShareFY2a;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "book_value_fy2a", precision = 19, scale = 4)
//	private BigDecimal bookValueFY2a;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "ebitd_fy2a", precision = 19, scale = 4)
//	private BigDecimal ebitdFY2a;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "sales_fy2a", precision = 19, scale = 4)
//	private BigDecimal salesFY2a;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "price_to_earnings_fy2a", precision = 19, scale = 4)
//	private BigDecimal priceToEarningsFY2a;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "price_to_cash_flow_fy2a", precision = 19, scale = 4)
//	private BigDecimal priceToCashFlowFY2a;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "price_to_book_fy2a", precision = 19, scale = 4)
//	private BigDecimal priceToBookFY2a;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "price_to_ebitd_fy2a", precision = 19, scale = 4)
//	private BigDecimal priceToEbitdaFY2a;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "market_cap_to_sales_fy2a", precision = 19, scale = 4)
//	private BigDecimal marketCapToSalesFY2a;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "eps_fy3", precision = 19, scale = 4)
//	private BigDecimal epsFY3;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "cash_flow_per_share_fy3", precision = 19, scale = 4)
//	private BigDecimal cashFlowPerShareFY3;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "sales_fy3", precision = 19, scale = 4)
//	private BigDecimal salesFY3;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "book_value_fy3", precision = 19, scale = 4)
//	private BigDecimal bookValueFY3;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "ebitd_fy3", precision = 19, scale = 4)
//	private BigDecimal ebitdFY3;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "price_to_earnings_fy3", precision = 19, scale = 4)
//	private BigDecimal priceToEarningsFY3;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "price_to_cash_flow_fy3", precision = 19, scale = 4)
//	private BigDecimal priceToCashFlowFY3;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "price_to_book_fy3", precision = 19, scale = 4)
//	private BigDecimal priceToBookFY3;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "price_to_ebitd_fy3", precision = 19, scale = 4)
//	private BigDecimal priceToEbitdaFY3;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "market_cap_to_sales_fy3", precision = 19, scale = 4)
//	private BigDecimal marketCapToSalesFY3;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "return_on_equity_fy3", precision = 19, scale = 4)
//	private BigDecimal returnOnEquityFY3;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "eps_fy3a", precision = 19, scale = 4)
//	private BigDecimal epsFY3a;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "cash_flow_per_share_fy3a", precision = 19, scale = 4)
//	private BigDecimal cashFlowPerShareFY3a;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "sales_fy3a", precision = 19, scale = 4)
//	private BigDecimal salesFY3a;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "book_value_fy3a", precision = 19, scale = 4)
//	private BigDecimal bookValueFY3a;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "ebitd_fy3a", precision = 19, scale = 4)
//	private BigDecimal ebitdFY3a;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "price_to_earnings_fy3a", precision = 19, scale = 4)
//	private BigDecimal priceToEarningsFY3a;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "price_to_cash_flow_fy3a", precision = 19, scale = 4)
//	private BigDecimal priceToCashFlowFY3a;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "price_to_book_fy3a", precision = 19, scale = 4)
//	private BigDecimal priceToBookFY3a;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "price_to_ebitd_fy3a", precision = 19, scale = 4)
//	private BigDecimal priceToEbitdaFY3a;
//	
//	@Type(type = CustomBigDecimal.HIBERNATE_TYPE_NAME)
//	@Column(name = "market_cap_to_sales_fy3a", precision = 19, scale = 4)
//	private BigDecimal marketCapToSalesFY3a;

	/**
	 * In DESC order
	 */
	@Override
	public int compareTo(LibraStockIndicators o) {
		// TODO Auto-generated method stub
		return o.getStampDate().compareTo(this.stampDate);
	}

}
