package com.libra.apollo.analytics.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.libra.apollo.analytics.entity.listener.PreventUpdateListener;

@Entity
@Table(name = "stockindicators")
@EntityListeners(PreventUpdateListener.class)
public class LibraStockIndicators extends AutoGeneratedId implements Comparable<LibraStockIndicators> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 222263006260457523L;

	@Temporal(TemporalType.DATE)
	@Column(name = "stamp_date", nullable = false)
	private Date stampDate;

	public Date getStampDate() {
		return stampDate;
	}

	public void setStampDate(Date stampDate) {
		this.stampDate = stampDate;
	}

	/**
	 * In DESC order
	 */
	@Override
	public int compareTo(LibraStockIndicators o) {
		// TODO Auto-generated method stub
		return o.getStampDate().compareTo(this.stampDate);
	}

}
