package com.libra.apollo.analytics.entity;

import javax.persistence.Column;
import javax.persistence.DiscriminatorColumn;
import javax.persistence.DiscriminatorType;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.Table;

import com.libra.apollo.analytics.entity.enums.InstrumentDataFieldType;

@SuppressWarnings("serial")
@Entity
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(name = "type", discriminatorType = DiscriminatorType.STRING)
@Table(name = "properties", schema = "analytics")
public abstract class Property extends AutoGeneratedId {

	@Column(name = "data_field_type", nullable = false)
	@Enumerated(EnumType.STRING)
	private InstrumentDataFieldType dataFieldType;

	@Column(name = "parameter", nullable = true)
	private double parameter;

	public InstrumentDataFieldType getDataFieldType() {
		return dataFieldType;
	}

	public void setDataFieldType(InstrumentDataFieldType dataFieldType) {
		this.dataFieldType = dataFieldType;
	}

	public double getParameter() {
		return parameter;
	}

	public void setParameter(double parameter) {
		this.parameter = parameter;
	}

}
