package com.libra.apollo.analytics.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Immutable;

import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;


//@SuppressWarnings("serial")
//@Entity
//@Table(name = "stockprices", schema = "apollo")
//@Immutable
public class StockPrice extends AutoGeneratedId implements Comparable<StockPrice> {

	@Column(name = "instrument_id")
	private Long stockId;

	@Temporal(TemporalType.DATE)
	@Column(name = "stamp_date", nullable = false)
	private Date stampDate;
	
	@Column(name = "open_price")
	private Double openPrice;
	
	@Column(name = "high_price")
	private Double highPrice;
	
	@Column(name = "low_price")
	private Double lowPrice;
	
	@Column(name = "close_price")
	private Double closePrice;
	
	@Column(name = "volume")
	private Double volume;

	@Column(name = "close_price_1d")
	private Double closePrice1D;
	
	@Column(name = "close_price_5d")
	private Double closePrice5D;
	
	
	@Column(name = "close_price_3m")
	private Double closePrice3M;
	
	public Long getStockId() {
		return stockId;
	}
	public void setStockId(Long stockId) {
		this.stockId = stockId;
	}
	
	public Date getStampDate() {
		return stampDate;
	}
	public void setStampDate(Date stampDate) {
		this.stampDate = stampDate;
	}
	public Double getOpenPrice() {
		return openPrice;
	}
	public void setOpenPrice(Double openPrice) {
		this.openPrice = openPrice;
	}
	public Double getHighPrice() {
		return highPrice;
	}
	public void setHighPrice(Double highPrice) {
		this.highPrice = highPrice;
	}
	public Double getLowPrice() {
		return lowPrice;
	}
	public void setLowPrice(Double lowPrice) {
		this.lowPrice = lowPrice;
	}
	public Double getClosePrice() {
		return closePrice;
	}
	public void setClosePrice(Double closePrice) {
		this.closePrice = closePrice;
	}
	public Double getVolume() {
		return volume;
	}
	public void setVolume(Double volume) {
		this.volume = volume;
	}
	public Double getClosePrice1D() {
		return closePrice1D;
	}
	public void setClosePrice1D(Double closePrice1D) {
		this.closePrice1D = closePrice1D;
	}
	public Double getClosePrice5D() {
		return closePrice5D;
	}
	public void setClosePrice5D(Double closePrice5D) {
		this.closePrice5D = closePrice5D;
	}
	public Double getClosePrice3M() {
		return closePrice3M;
	}
	public void setClosePrice3M(Double closePrice3M) {
		this.closePrice3M = closePrice3M;
	}
	
	@Override
	public boolean equals(final Object obj) {
		if (obj == null)
			return false;
		if (this == obj)
			return true;
		if (obj.getClass() != getClass()) { return false; }
		StockPrice other = (StockPrice) obj;
		return Objects.equal(this.stockId, other.stockId)
	            && Objects.equal(this.stampDate, other.stampDate)
	            && Objects.equal(this.closePrice, other.closePrice);
	}

	@Override
    public int hashCode() {
        return Objects.hashCode(
            this.stockId, this.stampDate, this.closePrice);

    }
	
	@Override
    public String toString() {

        return MoreObjects.toStringHelper(this)
            .add("stockId", this.stockId)
            .add("stampDate", stampDate)
            .add("closePrice", closePrice)
            .toString();

    }
	@Override
	public int compareTo(StockPrice o) {
		return this.getStampDate().compareTo(o.getStampDate());
	}
	
	
	
	
}
