	drop table analytics.analytics if EXISTS;
	drop table analytics.analytics_data_source if EXISTS;
	drop table analytics.analytics_investment_style if EXISTS;
	drop table analytics.analytics_investment_style if EXISTS;
	drop table analytics.analytics_investment_style_parameter if EXISTS;
	drop table analytics.analytics_investment_style_parameter if EXISTS;
	drop table analytics.analytics_parameter if EXISTS;
	drop table analytics.analytics_view if EXISTS;


	create table analytics.analytics (
        id bigint generated by default as identity,
        created_on timestamp not null,
        updated_on timestamp not null,
        version integer not null,
        description varchar(255),
        name varchar(255) not null,
        run_type varchar(255) not null,
        analytics_type varchar(255) not null,
        primary key (id)
    );
 
    
	create table analytics.analytics_data_source (
        id bigint generated by default as identity,
        created_on timestamp not null,
        updated_on timestamp not null,
        version integer not null,
        clazz_name varchar(255),
        type varchar(255) not null,
        url_base varchar(255),
        primary key (id)
    );
    
	create table analytics.analytics_investment_style (
        id bigint generated by default as identity,
        created_on timestamp not null,
        updated_on timestamp not null,
        version integer not null,
        description varchar(255),
        name varchar(255) not null,
        priority integer,
        analytics_id bigint,
        parent_id bigint,
        view_id bigint,
        primary key (id)
    );
    
	create table analytics.analytics_investment_style_parameter (
        id bigint generated by default as identity,
        priority integer,
        data_source_id bigint,
        investment_style_id bigint,
        parameter_id bigint,
        primary key (id)
    );

 	create table analytics.analytics_parameter (
        type varchar(31) not null,
        id bigint generated by default as identity,
        created_on timestamp not null,
        updated_on timestamp not null,
        version integer not null,
        composition_type varchar(255),
        data_field_type varchar(255),
        operand varchar(255),
        id_value bigint,
        double_value double,
        date_value timestamp,
        decimal_value decimal(19,2),
        list_of_id_parameter bigint,
        primary key (id)
    );

	create table analytics.analytics_view (
        id bigint generated by default as identity,
        created_on timestamp not null,
        updated_on timestamp not null,
        version integer not null,
        description varchar(255),
        name varchar(255) not null,
        priority integer,
        analytics_id bigint,
        parent_id bigint,
        primary key (id)
    );


	create index analytics.type_idx on analytics.analytics (analytics_type);
	create index analytics.run_type_idx on analytics.analytics (run_type);


	alter table analytics.analytics_investment_style 
        add constraint FKhn8kvfhtvux5bluebrlcus8pr 
        foreign key (analytics_id) 
        references analytics.analytics

	alter table analytics.analytics_investment_style 
        add constraint FKisp24obbnhvcucqe5bve6h9yd 
        foreign key (parent_id) 
        references analytics.analytics_investment_style

    alter table analytics.analytics_investment_style 
        add constraint FKds97b40e7wdpok24a7lpxmd0 
        foreign key (view_id) 
        references analytics.analytics_view

    alter table analytics.analytics_investment_style 
        add constraint FKds97b40e7wdpok24a7lpxmd0 
        foreign key (view_id) 
        references analytics.analytics_view 
        
    alter table analytics.analytics_investment_style_parameter 
        add constraint FK3j52t39vw5fgu06us8g1u53j4 
        foreign key (data_source_id) 
        references analytics.analytics_data_source

 
    alter table analytics.analytics_investment_style_parameter 
        add constraint FKl0djprx4sav63nad74m4wkt13 
        foreign key (investment_style_id) 
        references analytics.analytics_investment_style

                      : 
    alter table analytics.analytics_investment_style_parameter 
        add constraint FK22a7xvu9caduxx7lh2qcouke4 
        foreign key (parameter_id) 
        references analytics.analytics_parameter

    alter table analytics.analytics_parameter 
        add constraint FKt3jb0g8ldqm08or4uwgk16dw3 
        foreign key (list_of_id_parameter) 
        references analytics.analytics_parameter
                    
    alter table analytics.analytics_view 
        add constraint FKma8jnkly15fgf3r4ayn9uybrt 
        foreign key (analytics_id) 
        references analytics.analytics
                 
    alter table analytics.analytics_view 
        add constraint FKptjwdubiog4vq0aryvb3jtbts 
        foreign key (parent_id) 
        references analytics.analytics_view

   
